import { pgTable, uuid, text, boolean, integer, jsonb, timestamp, index } from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'
import { organizations } from './organizations'
import { categories } from './categories'
import { contacts } from './contacts'

const tz = { withTimezone: true }

export const categorizationRules = pgTable(
  'categorization_rules',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    // condições de ativação: { field: 'description', op: 'contains', value: 'ALUGUEL' }
    conditions: jsonb('conditions').notNull(),
    targetCategoryId: uuid('target_category_id')
      .notNull()
      .references(() => categories.id),
    targetContactId: uuid('target_contact_id').references(() => contacts.id),
    // prioridade: maior número = checado primeiro
    priority: integer('priority').notNull().default(0),
    // true = sugestão do expert aguardando confirmação; false = criada pelo usuário
    autoGenerated: boolean('auto_generated').notNull().default(false),
    confirmedAt: timestamp('confirmed_at', tz),
    isActive: boolean('is_active').notNull().default(true),
    matchCount: integer('match_count').notNull().default(0),
    createdByUserId: uuid('created_by_user_id'),
    createdAt: timestamp('created_at', tz).notNull().default(sql`now()`),
    updatedAt: timestamp('updated_at', tz).notNull().default(sql`now()`),
  },
  (t) => ({
    activeRulesIdx: index('idx_rules_org_active')
      .on(t.organizationId, t.isActive)
      .where(sql`${t.isActive} = true`),
    priorityIdx: index('idx_rules_priority').on(t.organizationId, t.priority),
  })
)

export type CategorizationRule = typeof categorizationRules.$inferSelect
export type NewCategorizationRule = typeof categorizationRules.$inferInsert
